openapi: 3.0.0
info:
  title: transaction-service
  version: 1.0.0
servers:
  - url: https://api.dev.halth.com
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
  parameters: {}
paths:
  /businesses/{businessId}/transactions:
    post:
      security:
        - bearer: []
      tags:
        - Transactions
      summary: Create transaction
      description:
        Transactions may involve payment, funding, or both. Funding will be
        processed first and then the gap payment is calculated.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currency:
                  type: string
                  enum: &a1
                    - aud
                bookingId:
                  type: string
                reason:
                  type: string
                  enum:
                    - standard
                    - late_cancellation
                    - no_show
                service:
                  type: object
                  properties:
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                            description: Unique identifier for the transaction item
                            example: "1"
                          chargeAmount:
                            anyOf:
                              - type: integer
                                minimum: 0
                                maximum: 9999999
                                description: Charge amount in cents
                                example: 10005
                              - type: number
                                enum:
                                  - 0
                          itemCode:
                            type: string
                          description:
                            type: string
                          clinicalCode:
                            type: string
                          isICDCode:
                            type: boolean
                        required:
                          - chargeAmount
                          - description
                      minItems: 1
                  required:
                    - items
                funding:
                  type: object
                  properties:
                    healthFundCardId:
                      type: string
                    patient:
                      type: object
                      properties:
                        location:
                          type: object
                          properties:
                            longitude:
                              type: number
                            latitude:
                              type: number
                            altitude:
                              type: number
                            accuracy:
                              type: number
                          required:
                            - longitude
                            - latitude
                      required:
                        - location
                  required:
                    - healthFundCardId
                    - patient
                payment:
                  type: object
                  properties:
                    paymentMethodId:
                      type: string
                  required:
                    - paymentMethodId
              required:
                - currency
                - bookingId
                - reason
                - service
                - payment
      responses:
        "201":
          description: Transaction created
    get:
      security:
        - bearer: []
      tags:
        - Transactions
      summary: Get transactions
      description: Get all transactions for a business.
      responses:
        "200":
          description: Transaction confirmed
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  businessId:
                    type: string
                  createdAt:
                    type: string
                  status:
                    type: string
                    enum:
                      - pending
                      - completed
                      - requires_confirmation
                      - requires_payment
                      - reversed
                      - failed
                  paymentTransactions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        createdAt:
                          type: string
                        source:
                          type: string
                          enum:
                            - client
                            - phi
                        amount:
                          type: number
                        paymentId:
                          type: string
                        payment:
                          nullable: true
                        claimId:
                          type: string
                        claim:
                          nullable: true
                        status:
                          type: string
                          enum:
                            - pending
                            - confirmed
                            - reversed
                            - requires_confirmation
                            - requires_payment
                            - failed
                      required:
                        - id
                        - createdAt
                        - source
                        - amount
                        - status
                  amount:
                    type: number
                  currency:
                    type: string
                    enum: *a1
                  transactionItems:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Unique identifier for the transaction item
                          example: "1"
                        chargeAmount:
                          anyOf:
                            - type: integer
                              minimum: 0
                              maximum: 9999999
                              description: Charge amount in cents
                              example: 10005
                            - type: number
                              enum:
                                - 0
                        itemCode:
                          type: string
                        description:
                          type: string
                        clinicalCode:
                          type: string
                        isICDCode:
                          type: boolean
                      required:
                        - chargeAmount
                        - description
                  confirmations:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        createdAt:
                          type: string
                        contactType:
                          type: string
                          enum:
                            - mobile
                        contactValue:
                          type: string
                        verified:
                          type: boolean
                        verifiedAt:
                          type: string
                        verificationCode:
                          type: string
                        action:
                          type: string
                          enum:
                            - claim_confirmation
                            - claim_cancellation
                        expiresAt:
                          type: string
                      required:
                        - id
                        - createdAt
                        - contactType
                        - contactValue
                        - verified
                        - action
                        - expiresAt
                  paymentMethodId:
                    type: string
                  paymentMethod:
                    nullable: true
                  healthFundCardId:
                    type: string
                  healthFundCard:
                    nullable: true
                  bookingId:
                    type: string
                  customer:
                    type: object
                    properties:
                      name:
                        type: string
                required:
                  - id
                  - businessId
                  - createdAt
                  - status
                  - paymentTransactions
                  - amount
                  - currency
                  - transactionItems
                  - confirmations
                  - customer
  /businesses/{businessId}/transactions/{transactionId}/confirm:
    post:
      security:
        - bearer: []
      tags:
        - Transactions
      summary: Confirm transaction
      description: Confirm a transaction and process the gap payment.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                verification:
                  type: object
                  properties:
                    verificationCode:
                      type: string
                      minLength: 4
                      maxLength: 4
                  required:
                    - verificationCode
              required:
                - verification
      responses:
        "200":
          description: Transaction confirmed
